name: CIMEL auto plotting

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora; ajusta según lo necesites
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Especifica la versión de Python que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de tener un requirements.txt

    - name: Run cimel plotting
      run: |
        python download_cimel.py  # Ejecuta tu script
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generadoauto"
        git push      


    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: main  # O la rama que uses para GitHub Pages
