name: Goes download

on:
  schedule:
    - cron: '30 1 * * *'  # Ejecuta todos los días a las 15:00 UTC
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener un requirements.txt

      - name: Run download script
        run: |
          python download_goes.py  # Ejecuta tu script


      - name: Run plotting composite script
        run: |
          python plot_composite.py  # Ejecuta tu script
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generadoauto"
          git push          
      - name: List files
        run: ls -la
